const SERVER_DEFAULTS = Object.freeze({
    DEFAULT_PORT: 5000
});

const SECURITY_DEFAULTS = Object.freeze({
    TRUST_PROXY: false,
    API_BODY_LIMIT: '1mb',
    URLENCODED_BODY_LIMIT: '1mb',
    DEFAULT_RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000,
    DEFAULT_RATE_LIMIT_MAX: 100000, // Temporarily increased to allow recovery from loop
    ENABLE_DEFAULT_RATE_LIMIT: false, // Temporarily disabled to unblock
    AUTH_LOGIN_RATE_LIMIT_WINDOW_MS: 10 * 60 * 1000,
    AUTH_LOGIN_RATE_LIMIT_MAX: 100, // Temporarily increased
    AUTH_LOGIN_FAILURE_WINDOW_MS: 15 * 60 * 1000,
    AUTH_LOGIN_LOCKOUT_MAX_FAILURES: 5,
    AUTH_LOGIN_LOCKOUT_MS: 15 * 60 * 1000,
    UPLOAD_RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000,
    UPLOAD_RATE_LIMIT_MAX: 30,
    ADMIN_ANALYTICS_RATE_LIMIT_WINDOW_MS: 5 * 60 * 1000,
    ADMIN_ANALYTICS_RATE_LIMIT_MAX: 100,
    GOAL_REPORT_RATE_LIMIT_WINDOW_MS: 5 * 60 * 1000,
    GOAL_REPORT_RATE_LIMIT_MAX: 100,
    UPLOAD_MAX_FILE_SIZE_MB: 50,
    ALLOWED_METHODS: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
    ALLOWED_HEADERS: ['Content-Type', 'Authorization'],
    LOCAL_ALLOWED_ORIGINS: ['http://localhost:5173', 'http://localhost:3000']
});

const TRANSACTION_TIMEOUTS = Object.freeze({
    DEFAULT_MAX_WAIT: 5000,
    DEFAULT_TIMEOUT: 10000,
    LONG_RUNNING_TIMEOUT: 15000
});

module.exports = {
    SERVER_DEFAULTS,
    SECURITY_DEFAULTS,
    TRANSACTION_TIMEOUTS
};
