const USER_PERMISSIONS = Object.freeze({
    SUPERADMIN: 'superadmin',
    ADMIN: 'admin',
    MANAGER: 'manager',
    USER: 'user'
});

const ADMIN_PANEL_PERMISSIONS = Object.freeze([
    USER_PERMISSIONS.SUPERADMIN,
    USER_PERMISSIONS.ADMIN,
    USER_PERMISSIONS.MANAGER
]);

const MANAGED_USER_PERMISSIONS = Object.freeze([
    USER_PERMISSIONS.USER,
    USER_PERMISSIONS.MANAGER
]);

// Aliases for compatibility
const USER_ROLES = USER_PERMISSIONS;
const ADMIN_PANEL_ROLES = ADMIN_PANEL_PERMISSIONS;
const MANAGED_USER_ROLES = MANAGED_USER_PERMISSIONS;

module.exports = {
    USER_PERMISSIONS,
    ADMIN_PANEL_PERMISSIONS,
    MANAGED_USER_PERMISSIONS,
    USER_ROLES,
    ADMIN_PANEL_ROLES,
    MANAGED_USER_ROLES
};
