const puppeteer = require('puppeteer-core');
const chromium = require('@sparticuz/chromium');
const supabase = require('../../utils/supabase');

// Singleton promise to ensure chromium.executablePath() is only called once per instance
let executablePathPromise = null;

function stringifyError(error) {
  return error?.stack || error?.message || String(error || 'Unknown error');
}

function buildLaunchDiagnostics(executablePath) {
  return [
    `platform=${process.platform}`,
    `arch=${process.arch}`,
    `node=${process.version}`,
    `executablePath=${executablePath || 'not resolved'}`
  ].join(' | ');
}

function escapePdfText(value) {
  return String(value || '')
    .replace(/[^\x20-\x7E\u0E00-\u0E7F]/g, '?')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function createSimpleCertificatePdf(data = {}) {
  const lines = [
    { text: 'CERTIFICATE OF COMPLETION', size: 26, x: 230, y: 500 },
    { text: data.learnerName || 'Learner', size: 18, x: 90, y: 430 },
    { text: `has completed: ${data.courseTitle || 'Course'}`, size: 16, x: 90, y: 390 },
    { text: `Certificate No: ${data.certificateNo || '-'}`, size: 12, x: 90, y: 330 },
    { text: `Issued: ${data.issuedAt || '-'}`, size: 12, x: 90, y: 305 },
    { text: `Verify: ${data.verificationUrl || '-'}`, size: 10, x: 90, y: 260 },
    { text: 'Generated by ScaleUp LMS', size: 10, x: 90, y: 90 }
  ];

  const content = [
    'q',
    '2 w',
    '40 40 762 515 re S',
    '0.95 0.97 1 rg',
    '52 52 738 491 re f',
    '0 0 0 rg',
    ...lines.flatMap(({ text, size, x, y }) => [
      'BT',
      `/F1 ${size} Tf`,
      `${x} ${y} Td`,
      `(${escapePdfText(text)}) Tj`,
      'ET'
    ]),
    'Q'
  ].join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${Buffer.byteLength(content, 'utf8')} >>\nstream\n${content}\nendstream`
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets[index + 1] = Buffer.byteLength(pdf, 'utf8');
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i <= objects.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, 'utf8');
}

async function getExecutablePath() {
  if (executablePathPromise) return executablePathPromise;
  
  executablePathPromise = (async () => {
    const configuredPath = process.env.CHROME_EXECUTABLE_PATH || process.env.PUPPETEER_EXECUTABLE_PATH;
    if (configuredPath) return configuredPath;

    try {
      return await chromium.executablePath();
    } catch (error) {
      console.error('[CertificatePdf] Failed to resolve chromium path:', error);
      executablePathPromise = null; // Reset for retry on next call
      return null;
    }
  })();
  
  return executablePathPromise;
}

/**
 * Generates a PDF buffer from HTML content using Puppeteer.
 * 
 * @param {String} html - The full HTML document
 * @param {Object} options - PDF options (orientation, format)
 * @returns {Buffer} PDF buffer
 */
async function generatePdfBuffer(html, options = {}) {
  // 1. Resolve executable path
  const executablePath = await getExecutablePath();
  const usesPackagedChromium = executablePath && executablePath.includes('/tmp/chromium');
  const fallbackData = options.fallbackData;

  const launchOptions = {
    args: executablePath && usesPackagedChromium ? chromium.args : ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    defaultViewport: chromium.defaultViewport,
    executablePath: executablePath || (process.platform === 'win32' 
      ? 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' 
      : '/usr/bin/google-chrome'),
    headless: usesPackagedChromium ? chromium.headless : 'new',
    ignoreHTTPSErrors: true,
  };

  try {
    // 2. Launch with aggressive retry to handle ETXTBSY race conditions
    let browser;
    let lastError;
    for (let i = 0; i < 5; i++) {
      try {
        browser = await puppeteer.launch(launchOptions);
        break;
      } catch (error) {
        lastError = error;
        const errorText = stringifyError(error);
        const isBusy = errorText.includes('ETXTBSY') || error.code === 'ETXTBSY';
        if (isBusy && i < 4) {
          const delay = 1000 + (Math.random() * 1000); // Random delay 1-2s
          console.warn(`[CertificatePdf] Browser launch busy (attempt ${i + 1}/5), retrying in ${Math.round(delay)}ms...`);
          await new Promise(resolve => setTimeout(resolve, delay));
          continue;
        }
        throw error;
      }
    }

    if (!browser) throw lastError;

    try {
      const page = await browser.newPage();
      
      // Set viewport size if needed, but A4 format usually takes care of it
      // Set content with a reasonable timeout for Vercel
      await page.setContent(html, { 
        waitUntil: 'load',
        timeout: 30000 
      });

      const pdfBuffer = await page.pdf({
        format: 'A4',
        landscape: options.orientation === 'LANDSCAPE',
        printBackground: true,
        margin: {
          top: options.marginTop || '0px',
          right: options.marginRight || '0px',
          bottom: options.marginBottom || '0px',
          left: options.marginLeft || '0px'
        }
      });

      return pdfBuffer;
    } finally {
      await browser.close();
    }
  } catch (error) {
    const errorText = stringifyError(error);
    const diagnostics = buildLaunchDiagnostics(executablePath);
    const missingLinuxLibrary = process.platform === 'linux' && /error while loading shared libraries|libnss3\.so/i.test(errorText);
    const message = missingLinuxLibrary
      ? `${errorText}\nCertificate PDF generation requires Chromium runtime libraries. Install libnss3 and standard Chromium dependencies, or set CHROME_EXECUTABLE_PATH to a working Chrome/Chromium binary. ${diagnostics}`
      : `${errorText}\nChromium PDF rendering failed. ${diagnostics}`;

    if (fallbackData) {
      console.warn(`[CertificatePdf] Chromium render failed; using simple PDF fallback. ${message}`);
      return createSimpleCertificatePdf({
        ...fallbackData,
        fallbackReason: message
      });
    }

    throw new Error(message);
  }
}

/**
 * Uploads the certificate PDF buffer to Supabase Storage.
 * 
 * @param {Object} params
 * @param {Buffer} params.buffer - The PDF buffer
 * @param {String} params.userId - User ID for the folder path
 * @param {String} params.certificateId - Certificate ID for the filename
 * @returns {String} Public URL or storage path
 */
async function uploadCertificatePdf({ buffer, userId, certificateId }) {
  const bucketName = 'uploads';
  const filePath = `certificates/${userId}/${certificateId}.pdf`;

  const { error } = await supabase.storage
    .from(bucketName)
    .upload(filePath, buffer, {
      contentType: 'application/pdf',
      upsert: true
    });

  if (error) {
    throw new Error(`Failed to upload to Supabase Storage: ${error.message}`);
  }

  // NOTE: We return only the file path for security. 
  // Access will be granted via temporary signed URLs.
  return filePath;
}

module.exports = {
  generatePdfBuffer,
  uploadCertificatePdf
};
