const puppeteer = require('puppeteer-core');
const chromium = require('@sparticuz/chromium');
const supabase = require('../../utils/supabase');

// Singleton promise to ensure chromium.executablePath() is only called once per instance
let executablePathPromise = null;

function stringifyError(error) {
  return error?.stack || error?.message || String(error || 'Unknown error');
}

function buildLaunchDiagnostics(executablePath) {
  return [
    `platform=${process.platform}`,
    `arch=${process.arch}`,
    `node=${process.version}`,
    `executablePath=${executablePath || 'not resolved'}`
  ].join(' | ');
}

function escapePdfText(value) {
  // Simple PDF strings () don't support Thai/Unicode. 
  // We'll replace non-ASCII with ? to avoid mojibake in the fallback,
  // but the GOAL is to make the primary Puppeteer flow work.
  return String(value || '')
    .replace(/[^\x20-\x7E]/g, '?') 
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function createSimpleCertificatePdf(data = {}) {
  const lines = [
    { text: 'CERTIFICATE OF COMPLETION', size: 26, x: 230, y: 500 },
    { text: data.learnerName || 'Learner', size: 18, x: 90, y: 430 },
    { text: `has completed: ${data.courseTitle || 'Course'}`, size: 16, x: 90, y: 390 },
    { text: `Certificate No: ${data.certificateNo || '-'}`, size: 12, x: 90, y: 330 },
    { text: `Issued: ${data.issuedAt || '-'}`, size: 12, x: 90, y: 305 },
    { text: `Verify: ${data.verificationUrl || '-'}`, size: 10, x: 90, y: 260 },
    { text: 'SYSTEM FALLBACK - GENERATION ERROR DETAILS:', size: 10, x: 90, y: 180 },
    { text: (data.fallbackReason || 'Unknown error').slice(0, 100), size: 8, x: 90, y: 160 },
    { text: (data.fallbackReason || '').slice(100, 200), size: 8, x: 90, y: 145 },
    { text: 'Generated by ScaleUp LMS', size: 10, x: 90, y: 90 }
  ];

  const content = [
    'q',
    '2 w',
    '40 40 762 515 re S',
    '0.95 0.97 1 rg',
    '52 52 738 491 re f',
    '0 0 0 rg',
    ...lines.flatMap(({ text, size, x, y }) => [
      'BT',
      `/F1 ${size} Tf`,
      `${x} ${y} Td`,
      `(${escapePdfText(text)}) Tj`,
      'ET'
    ]),
    'Q'
  ].join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${Buffer.byteLength(content, 'utf8')} >>\nstream\n${content}\nendstream`
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets[index + 1] = Buffer.byteLength(pdf, 'utf8');
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i <= objects.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, 'utf8');
}

async function getExecutablePath() {
  if (executablePathPromise) return executablePathPromise;
  
  executablePathPromise = (async () => {
    const configuredPath = process.env.CHROME_EXECUTABLE_PATH || process.env.PUPPETEER_EXECUTABLE_PATH;
    if (configuredPath) return configuredPath;

    try {
      return await chromium.executablePath();
    } catch (error) {
      console.error('[CertificatePdf] Failed to resolve chromium path:', error);
      executablePathPromise = null; // Reset for retry on next call
      return null;
    }
  })();
  
  return executablePathPromise;
}

/**
 * Generates a PDF buffer from HTML content using Puppeteer.
 * 
 * @param {String} html - The full HTML document
 * @param {Object} options - PDF options (orientation, format)
 * @returns {Buffer} PDF buffer
 */
async function generatePdfBuffer(html, options = {}) {
  const fallbackData = options.fallbackData;

  try {
    const launchOptions = {
      args: [...chromium.args, '--hide-scrollbars', '--disable-web-security', '--no-sandbox'],
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    };

    let browser;
    let lastError;
    for (let i = 0; i < 3; i++) {
      try {
        browser = await puppeteer.launch(launchOptions);
        break;
      } catch (error) {
        lastError = error;
        console.error(`[CertificatePdf] Launch attempt ${i+1} failed:`, error);
        await new Promise(r => setTimeout(r, 1000));
      }
    }

    if (!browser) throw lastError;

    try {
      const page = await browser.newPage();
      
      // Use 'domcontentloaded' for faster response
      await page.setContent(html, { 
        waitUntil: 'domcontentloaded',
        timeout: 45000 
      });

      // Extra time for fonts
      await new Promise(resolve => setTimeout(resolve, 1000));

      const pdfBuffer = await page.pdf({
        format: 'A4',
        landscape: options.orientation === 'LANDSCAPE',
        printBackground: true,
        margin: {
          top: options.marginTop || '0px',
          right: options.marginRight || '0px',
          bottom: options.marginBottom || '0px',
          left: options.marginLeft || '0px'
        }
      });

      return pdfBuffer;
    } finally {
      await browser.close();
    }
  } catch (error) {
    const errorText = stringifyError(error);
    const message = `Chromium PDF rendering failed: ${errorText}`;

    if (fallbackData) {
      console.warn(`[CertificatePdf] Chromium render failed; using simple PDF fallback. ${message}`);
      return createSimpleCertificatePdf({
        ...fallbackData,
        fallbackReason: message
      });
    }

    throw new Error(message);
  }
}

/**
 * Uploads the certificate PDF buffer to Supabase Storage.
 * 
 * @param {Object} params
 * @param {Buffer} params.buffer - The PDF buffer
 * @param {String} params.userId - User ID for the folder path
 * @param {String} params.certificateId - Certificate ID for the filename
 * @returns {String} Public URL or storage path
 */
async function uploadCertificatePdf({ buffer, userId, certificateId }) {
  const bucketName = 'uploads';
  const filePath = `certificates/${userId}/${certificateId}.pdf`;

  const { error } = await supabase.storage
    .from(bucketName)
    .upload(filePath, buffer, {
      contentType: 'application/pdf',
      upsert: true
    });

  if (error) {
    throw new Error(`Failed to upload to Supabase Storage: ${error.message}`);
  }

  // NOTE: We return only the file path for security. 
  // Access will be granted via temporary signed URLs.
  return filePath;
}

module.exports = {
  generatePdfBuffer,
  uploadCertificatePdf
};
